### PR TITLE
Bug fixes and improvements for version 1.31.7 — EXT-64

### PR DESCRIPTION
**Pull request by phpbits**
This PR consists of the fixes for the following issues:

https://wordpress.org/support/topic/bug-in-the-settings-page/#post-14868497
https://wordpress.org/support/topic/link-on-block/
https://github.com/extendify/block-options/issues/336
https://github.com/extendify/editorskit-internal/issues/2
https://github.com/extendify/editorskit-internal/issues/3

This couple of tickets are not included in these improvements with the reason stated alongside the links.

https://wordpress.org/support/topic/visibility-settings-conditional-logic-stopped-working/ - It seems that `EDITORSKIT_ALLOW_EVAL` has been [added](https://github.com/extendify/block-options/blob/master/includes/class-editorskit-render-block.php#L166) and should be defined in order to use this feature.
https://wordpress.org/support/topic/shortcut-error-re-headings/- Headings shortcuts are only supposed to work on the Headings block only. It is still working as expected and the heading level is being transformed correctly.

Thanks!

### CODE REVIEW

**Comment by Salman0341** [comment]
I've tested this PR, I've noticed the following issues:

> https://wordpress.org/support/topic/bug-in-the-settings-page/#post-14868497

Fixed/Works fine.

> https://wordpress.org/support/topic/link-on-block/

About – Historic Sailfish - Google Chrome 2021-09-21 at 1 14 37 PM

If that means removing the 'rel' attribute completely, it's fixed.

> #336

This seems like not working properly, yet.

> extendify/editorskit-internal#2

Fixed/Works fine.

> https://github.com/extendify/editorskit-internal/issues/3

This seems to work on the front-end but not the editor.

### backend Screenshot

screenshot-historic-sailfish jurassic ninja-2021 09 21-13_19_39

### Editor Screenshot

screenshot-historic-sailfish jurassic ninja-2021 09 21-13_21_48


Note: While testing, I've noticed some other issues.

###  Font Family Issues
  
When we apply font-family it throws an error. FYI @phpbits 


screenshot-historic-sailfish jurassic ninja-2021 09 21-13_27_05

**Comment by Salman0341** [comment]
> Can you please share some additional details on what it means to not be working properly? Screenshots (like with the other issues) would be helpful.

Here is a quick screencast to show what happens if I apply the alignment option.


https://user-images.githubusercontent.com/73986322/134181928-9d37a622-070e-4979-97be-5e7e5fadbcbb.mp4

**Comment by phpbits** [comment]
> > Can you please share some additional details on what it means to not be working properly? Screenshots (like with the other issues) would be helpful.
> 
> Here is a quick screencast to show what happens if I apply the alignment option.
> 
>  screencast-nimbus-capture-2021.09.21-18_28_00.1.mp4

@Salman0341 The alignment options do not support the preview and the styles are only available in the frontend. Class names are also only being added in the front-end view. Thanks!

**Comment by phpbits** [comment]
@Salman0341 The Gapless columns style seems to be working on my end. Could you run `npm start` in order for the stylesheets to be updated? Thanks!

Screen Shot 2021-10-04 at 2 18 58 AM

**Comment by phpbits** [comment]
@Salman0341 The font family PHP log has been taken care of as well. Could you double-check the error using the `fix/bug-fixes-1.31.7` branch? Thanks!

**Comment by Salman0341** [comment]
Thanks, @phpbits  for the update. I've just re-tested and i can confirm that: 

1. font family error has disappeared.
2.  Gapless feature is working for me now.

**Pull request merged**
